import { cleanup, screen } from '@testing-library/react'
import { useLocation } from 'react-router'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { renderWithProviders } from '@/test/render'
import { CompetitorsTab } from './competitors-tab'

const hooks = vi.hoisted(() => ({ query: vi.fn(), search: vi.fn() }))
vi.mock('../hooks', () => ({
  useCompetitors: hooks.query,
  useRefreshCompetitors: hooks.search,
}))

const mutate = vi.fn()
const saved = {
  ticker: 'WDC', snapshot_id: 7, question: 'Who competes with WDC?',
  answer_markdown: 'Seagate (**STX**) competes in hard disk drives.',
  sources: [{ title: 'Western Digital annual report', publisher: 'Western Digital',
    url: 'https://investor.wdc.com/annual-report' }],
  generated_at: '2026-10-02T09:30:00Z', cached: true,
  caveat: 'Generated by Google Finance. Informational only.',
  source: { name: 'google_finance', ok: true, error: null,
    fetched_at: '2026-10-02T09:30:00Z', latency_ms: null },
}

beforeEach(() => {
  hooks.query.mockReturnValue({ data: null, isPending: false, isError: false,
    isFetching: false, refetch: vi.fn() })
  hooks.search.mockReturnValue({ data: undefined, isPending: false, isError: false, mutate })
})
afterEach(cleanup)

test('displays a compact saved result with sources collapsed and its original date', async () => {
  hooks.query.mockReturnValue({ data: saved, isPending: false, isError: false, isFetching: false })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByText('STX')).toBeInTheDocument()
  expect(screen.queryByRole('link', { name: /Western Digital annual report/ })).toBeNull()
  await userEvent.click(screen.getByRole('button', { name: 'Sources (1)' }))
  expect(screen.getByRole('link', { name: /Western Digital annual report/ }))
    .toHaveAttribute('href', 'https://investor.wdc.com/annual-report')
  const timestamp = document.querySelector('time')
  expect(timestamp).toHaveAttribute('datetime', '2026-10-02T09:30:00Z')
  expect(timestamp?.textContent).toContain('2026')
  expect(timestamp?.textContent).toBe('Oct 2, 2026, 5:30 AM ET')
  expect(screen.getByText(/Updated/)).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Refresh' })).toBeEnabled()
  expect(screen.queryByRole('button', { name: 'Find competitors' })).not.toBeInTheDocument()
})

test('a competitor ticker opens that stock page', async () => {
  hooks.query.mockReturnValue({ data: saved, isPending: false, isError: false, isFetching: false })
  function Location() {
    return <output aria-label="Current location">{useLocation().pathname}</output>
  }
  renderWithProviders(<><CompetitorsTab ticker="WDC" /><Location /></>, ['/stocks/WDC'])
  const ticker = screen.getByRole('link', { name: 'STX' })
  expect(ticker).toHaveAttribute('href', '/stocks/STX')
  await userEvent.click(ticker)
  expect(screen.getByLabelText('Current location')).toHaveTextContent('/stocks/STX')
})

test('long research stays hidden until opened while direct and indirect summaries remain visible', async () => {
  hooks.query.mockReturnValue({ data: { ...saved, answer_markdown: `Long market introduction.
### Direct Competitors
### Seagate Technology
- Ticker: NASDAQ:STX
- Explanation: Seagate competes in HDDs. Detailed technology commentary.
### Indirect Competitors
### Micron Technology
- Ticker: NASDAQ:MU
- Explanation: Micron supplies enterprise SSDs. Detailed memory commentary.
` }, isPending: false, isError: false, isFetching: false })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByRole('heading', { name: 'Direct competitors' })).toBeInTheDocument()
  expect(screen.getByRole('heading', { name: 'Indirect alternatives' })).toBeInTheDocument()
  expect(screen.getByRole('link', { name: 'STX' })).toBeInTheDocument()
  expect(screen.getByRole('link', { name: 'MU' })).toBeInTheDocument()
  expect(screen.queryByText(/Detailed technology commentary/)).toBeNull()
  expect(screen.queryByText('Long market introduction.')).toBeNull()
  await userEvent.click(screen.getByRole('button', { name: 'Show detailed research' }))
  expect(screen.getByText(/Detailed technology commentary/)).toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Hide detailed research' }))
  expect(screen.queryByText(/Detailed technology commentary/)).toBeNull()
})

test('unrecognized answer formats remain available in detailed research', async () => {
  hooks.query.mockReturnValue({ data: { ...saved, answer_markdown: 'No listed competitors could be confirmed.' }, isPending: false, isError: false, isFetching: false })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByText(/Open detailed research/)).toBeInTheDocument()
  await userEvent.click(screen.getByRole('button', { name: 'Show detailed research' }))
  expect(screen.getByText('No listed competitors could be confirmed.')).toBeInTheDocument()
})

test('requires an explicit first search and explains that the answer is saved', async () => {
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByText(/saved for future visits/i)).toBeInTheDocument()
  expect(mutate).not.toHaveBeenCalled()
  await userEvent.click(screen.getByRole('button', { name: 'Find competitors' }))
  expect(mutate).toHaveBeenCalledTimes(1)
  expect(mutate).toHaveBeenCalledWith(false)
})

test('shows the failure and permits retry without labeling it as a saved response', () => {
  hooks.search.mockReturnValue({ data: { ...saved, snapshot_id: null, answer_markdown: null,
    source: { ...saved.source, ok: false, error: 'Google Finance unavailable' } },
    isPending: false, isError: false, mutate })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByText(/Google Finance unavailable/)).toBeInTheDocument()
  expect(screen.getByRole('button', { name: /Retry/ })).toBeEnabled()
  expect(document.querySelector('time')).toBeNull()
})

test('disables duplicate requests while the first search is pending', () => {
  hooks.search.mockReturnValue({ data: undefined, isPending: true, isError: false, mutate })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByRole('button', { name: /Searching/ })).toBeDisabled()
})

test('does not show the previous stocks mutation result after navigating to another ticker', () => {
  hooks.search.mockReturnValue({ data: saved, isPending: false, isError: false, mutate })
  const { rerender } = renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByText('STX')).toBeInTheDocument()
  rerender(<CompetitorsTab ticker="NVDA" />)
  expect(screen.queryByText('STX')).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Find competitors' })).toBeEnabled()
})

test('refresh explicitly requests a new response while leaving the saved answer visible', async () => {
  hooks.query.mockReturnValue({ data: saved, isPending: false, isError: false, isFetching: false })
  const { rerender } = renderWithProviders(<CompetitorsTab ticker="WDC" />)
  await userEvent.click(screen.getByRole('button', { name: 'Refresh' }))
  expect(mutate).toHaveBeenCalledWith(true)
  hooks.search.mockReturnValue({ data: undefined, isPending: true, isError: false, mutate })
  rerender(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByRole('button', { name: /Refreshing/ })).toBeDisabled()
  expect(screen.getByText('STX')).toBeInTheDocument()
})

test('shows refresh errors while preserving the old answer and date', () => {
  hooks.query.mockReturnValue({ data: saved, isPending: false, isError: false, isFetching: false })
  hooks.search.mockReturnValue({ data: { ...saved, snapshot_id: null, answer_markdown: null,
    source: { ...saved.source, ok: false, error: 'Refresh unavailable' } },
    isPending: false, isError: false, mutate })
  renderWithProviders(<CompetitorsTab ticker="WDC" />)
  expect(screen.getByRole('alert')).toHaveTextContent('Refresh unavailable')
  expect(screen.getByText('STX')).toBeInTheDocument()
  expect(document.querySelector('time')).toHaveAttribute('datetime', saved.generated_at)
  expect(screen.getByRole('button', { name: 'Refresh' })).toBeEnabled()
})
