import { cleanup, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { renderWithProviders } from '@/test/render'
import type { GoogleFinanceResearchOut } from '@/types/api'
import { GoogleFinanceResearch } from './google-finance-research'

const researchHook = vi.hoisted(() => vi.fn())

vi.mock('../hooks', () => ({
  useGoogleFinanceResearch: researchHook,
}))

const mutate = vi.fn()
const reset = vi.fn()

const success: GoogleFinanceResearchOut = {
  ticker: 'MSTR',
  question: 'Why today?',
  answer_markdown: 'MSTR moved with **Bitcoin**.',
  sources: [
    {
      title: 'MSTR rally explained',
      publisher: 'Example News',
      url: 'https://example.com/mstr',
    },
  ],
  generated_at: '2026-09-04T13:00:00Z',
  caveat: 'Generated by Google Finance. Informational only.',
  source: {
    name: 'google_finance',
    ok: true,
    fetched_at: '2026-09-04T13:00:00Z',
    error: null,
    latency_ms: 8000,
  },
}

function setHookState(overrides: Record<string, unknown> = {}) {
  researchHook.mockReturnValue({
    mutate,
    reset,
    data: undefined,
    error: null,
    isError: false,
    isPending: false,
    ...overrides,
  })
}

beforeEach(() => {
  mutate.mockReset()
  reset.mockReset()
  researchHook.mockReset()
  setHookState()
})

afterEach(cleanup)

test('starts with a ticker-aware prompt and submits edited text', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  const input = screen.getByRole('textbox', { name: 'Google Finance question' })
  expect(input).toHaveValue('Why is MSTR moving today?')
  await user.clear(input)
  await user.type(input, 'What changed after earnings?')
  await user.click(screen.getByRole('button', { name: 'Ask Google Finance' }))

  expect(mutate).toHaveBeenCalledWith('What changed after earnings?')
})

test('disables submission and shows progress while research is pending', () => {
  setHookState({ isPending: true })

  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.getByRole('textbox', { name: 'Google Finance question' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Researching…' })).toBeDisabled()
})

test('renders markdown, attribution, and safe source links', async () => {
  setHookState({ data: success })

  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(await screen.findByText('Bitcoin')).toBeInTheDocument()
  expect(screen.getByText('Why today?')).toBeInTheDocument()
  expect(screen.getByText('Generated by Google Finance. Informational only.')).toBeInTheDocument()
  const source = screen.getByRole('link', { name: 'MSTR rally explained' })
  expect(source).toHaveAttribute('href', 'https://example.com/mstr')
  expect(source).toHaveAttribute('target', '_blank')
  expect(source).toHaveAttribute('rel', 'noopener noreferrer')
  expect(screen.getByText('Example News')).toBeInTheDocument()
})

test('renders a degraded upstream error and keeps the question editable', async () => {
  const user = userEvent.setup()
  setHookState({
    data: {
      ...success,
      answer_markdown: null,
      sources: [],
      source: { ...success.source, ok: false, error: 'Google Finance page changed' },
    },
  })

  renderWithProviders(<GoogleFinanceResearch ticker="NVDA" />)

  expect(screen.getByText('Google Finance page changed')).toBeInTheDocument()
  const input = screen.getByRole('textbox', { name: 'Google Finance question' })
  await user.clear(input)
  await user.type(input, 'Try another question')
  expect(input).toHaveValue('Try another question')
})

test('renders a network error and always offers the direct Google fallback', () => {
  setHookState({ isError: true, error: new Error('Backend unavailable') })

  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.getByText('Backend unavailable')).toBeInTheDocument()
  const fallback = screen.getByRole('link', { name: 'Open Google Finance' })
  expect(fallback).toHaveAttribute('href', 'https://www.google.com/finance/beta/#research')
  expect(fallback).toHaveAttribute('target', '_blank')
  expect(fallback).toHaveAttribute('rel', 'noopener noreferrer')
})

test('replaces the displayed result when the mutation returns new data', () => {
  setHookState({ data: success })
  const rendered = renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  expect(screen.getByText('MSTR rally explained')).toBeInTheDocument()

  setHookState({
    data: {
      ...success,
      question: 'What are the risks?',
      answer_markdown: 'The main risk is **Bitcoin volatility**.',
      sources: [],
    },
  })
  rendered.rerender(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.queryByText('MSTR rally explained')).not.toBeInTheDocument()
  expect(screen.getByText('What are the risks?')).toBeInTheDocument()
  expect(screen.getByText('Bitcoin volatility')).toBeInTheDocument()
})

test('offers no Clear action until there is something to clear', () => {
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.queryByRole('button', { name: 'Clear' })).not.toBeInTheDocument()
})

test('Clear discards the answer and restores the default ticker question', async () => {
  const user = userEvent.setup()
  setHookState({ data: success })
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  const input = screen.getByRole('textbox', { name: 'Google Finance question' })
  await user.clear(input)
  await user.type(input, 'Some other question')

  await user.click(screen.getByRole('button', { name: 'Clear' }))

  expect(reset).toHaveBeenCalledTimes(1)
  expect(input).toHaveValue('Why is MSTR moving today?')
})

test('Clear is offered after a failed request too', () => {
  setHookState({ isError: true, error: new Error('Backend unavailable') })

  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.getByRole('button', { name: 'Clear' })).toBeEnabled()
})

test('Clear is unavailable while a request is in flight', () => {
  setHookState({ data: success, isPending: true })

  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.getByRole('button', { name: 'Clear' })).toBeDisabled()
})
