import { cleanup, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { renderWithProviders } from '@/test/render'
import type { GoogleFinanceResearchOut } from '@/types/api'
import { GoogleFinanceResearch } from './google-finance-research'

const researchHook = vi.hoisted(() => vi.fn())

vi.mock('../hooks', () => ({
  useGoogleFinanceResearch: researchHook,
}))

const mutateAsync = vi.fn()
const reset = vi.fn()

const success: GoogleFinanceResearchOut = {
  ticker: 'MSTR',
  question: 'Why today?',
  answer_markdown: 'MSTR moved with **Bitcoin**.',
  sources: [
    {
      title: 'MSTR rally explained',
      publisher: 'Example News',
      url: 'https://example.com/mstr',
    },
  ],
  generated_at: '2026-09-04T13:00:00Z',
  caveat: 'Generated by Google Finance. Informational only.',
  source: {
    name: 'google_finance',
    ok: true,
    fetched_at: '2026-09-04T13:00:00Z',
    error: null,
    latency_ms: 8000,
  },
}

function setHookState(overrides: Record<string, unknown> = {}) {
  researchHook.mockReturnValue({
    mutateAsync,
    reset,
    error: null,
    isError: false,
    isPending: false,
    ...overrides,
  })
}

async function openChat(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: /Ask Google Finance|Continue chat/ }))
}

beforeEach(() => {
  mutateAsync.mockReset()
  reset.mockReset()
  researchHook.mockReset()
  setHookState()
})

afterEach(cleanup)

test('shows a launcher button that opens the chat sheet', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  expect(screen.queryByRole('textbox', { name: 'Google Finance question' })).not.toBeInTheDocument()
  await openChat(user)

  expect(screen.getByRole('textbox', { name: 'Google Finance question' })).toBeInTheDocument()
  expect(screen.getByText('Ask about MSTR')).toBeInTheDocument()
})

test('submits edited text with no history yet', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValue(success)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  const input = screen.getByRole('textbox', { name: 'Google Finance question' })
  expect(input).toHaveValue('Why is MSTR moving today?')
  await user.clear(input)
  await user.type(input, 'What changed after earnings?')
  await user.click(screen.getByRole('button', { name: 'Submit' }))

  expect(mutateAsync).toHaveBeenCalledWith({
    question: 'What changed after earnings?',
    history: [],
  })
})

test('disables submission and shows progress while research is pending', async () => {
  const user = userEvent.setup()
  setHookState({ isPending: true })
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  expect(screen.getByRole('textbox', { name: 'Google Finance question' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Submit' })).toBeDisabled()
})

test('renders markdown, attribution, and safe source links after asking', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValue(success)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))

  const dialog = screen.getByRole('dialog')
  expect(await within(dialog).findByText('Bitcoin')).toBeInTheDocument()
  expect(within(dialog).getByText('Why today?')).toBeInTheDocument()
  expect(
    within(dialog).getByText('Generated by Google Finance. Informational only.'),
  ).toBeInTheDocument()
  const source = within(dialog).getByRole('link', { name: 'MSTR rally explained' })
  expect(source).toHaveAttribute('href', 'https://example.com/mstr')
  expect(source).toHaveAttribute('target', '_blank')
  expect(source).toHaveAttribute('rel', 'noopener noreferrer')
  expect(within(dialog).getByText('Example News')).toBeInTheDocument()
})

test('renders a degraded upstream turn inline and keeps the composer usable', async () => {
  const user = userEvent.setup()
  const degraded: GoogleFinanceResearchOut = {
    ...success,
    answer_markdown: null,
    sources: [],
    source: { ...success.source, ok: false, error: 'Google Finance page changed' },
  }
  mutateAsync.mockResolvedValue(degraded)
  renderWithProviders(<GoogleFinanceResearch ticker="NVDA" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))

  const dialog = screen.getByRole('dialog')
  expect(await within(dialog).findByText('Google Finance page changed')).toBeInTheDocument()
  const input = screen.getByRole('textbox', { name: 'Google Finance question' })
  await user.type(input, 'Try another question')
  expect(input).toHaveValue('Try another question')
})

test('renders a network error banner inside the sheet', async () => {
  const user = userEvent.setup()
  setHookState({ isError: true, error: new Error('Backend unavailable') })
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  expect(screen.getByText('Backend unavailable')).toBeInTheDocument()
})

test('always offers the direct Google Finance fallback link', () => {
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)

  const fallback = screen.getByRole('link', { name: 'Open Google Finance' })
  expect(fallback).toHaveAttribute('href', 'https://www.google.com/finance/beta/#research')
  expect(fallback).toHaveAttribute('target', '_blank')
  expect(fallback).toHaveAttribute('rel', 'noopener noreferrer')
})

test('accumulates turns into a thread and previews the latest one on the launcher card', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValueOnce(success)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))
  const dialog = screen.getByRole('dialog')
  expect(await within(dialog).findByText('MSTR rally explained')).toBeInTheDocument()
  // The launcher trigger behind the (open, so aria-hidden) sheet already relabels itself.
  expect(
    screen.getByRole('button', { name: 'Continue chat', hidden: true }),
  ).toBeInTheDocument()

  const second: GoogleFinanceResearchOut = {
    ...success,
    question: 'What are the risks?',
    answer_markdown: 'The main risk is **Bitcoin volatility**.',
    sources: [],
  }
  mutateAsync.mockResolvedValueOnce(second)
  await user.type(
    screen.getByRole('textbox', { name: 'Google Finance question' }),
    'What are the risks?',
  )
  await user.click(screen.getByRole('button', { name: 'Submit' }))

  expect(
    await within(dialog).findByText('Bitcoin volatility', { exact: false }),
  ).toBeInTheDocument()
  // The previous turn is still visible in the thread -- it accumulates, it doesn't replace.
  expect(within(dialog).getByText('MSTR rally explained')).toBeInTheDocument()
  // The launcher preview outside the sheet shows the latest turn's question.
  expect(screen.getAllByText('What are the risks?')).toHaveLength(2)
})

test('sends prior successful turns as history on the next question', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValue(success)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))
  await within(screen.getByRole('dialog')).findByText('MSTR rally explained')

  await user.type(
    screen.getByRole('textbox', { name: 'Google Finance question' }),
    'What about its competitor?',
  )
  await user.click(screen.getByRole('button', { name: 'Submit' }))

  expect(mutateAsync).toHaveBeenLastCalledWith({
    question: 'What about its competitor?',
    history: [{ question: 'Why today?', answer: 'MSTR moved with **Bitcoin**.' }],
  })
})

test('does not carry a degraded turn forward into history', async () => {
  const user = userEvent.setup()
  const degraded: GoogleFinanceResearchOut = {
    ...success,
    answer_markdown: null,
    sources: [],
    source: { ...success.source, ok: false, error: 'Google Finance page changed' },
  }
  mutateAsync.mockResolvedValueOnce(degraded)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))
  await within(screen.getByRole('dialog')).findByText('Google Finance page changed')

  mutateAsync.mockResolvedValueOnce(success)
  await user.type(
    screen.getByRole('textbox', { name: 'Google Finance question' }),
    'Try again please',
  )
  await user.click(screen.getByRole('button', { name: 'Submit' }))

  expect(mutateAsync).toHaveBeenLastCalledWith({
    question: 'Try again please',
    history: [],
  })
})

test('New chat is unavailable until there is something to clear', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  expect(screen.getByRole('button', { name: 'New chat' })).toBeDisabled()
})

test('New chat resets the thread and restores the default ticker question', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValueOnce(success)
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Submit' }))
  await within(screen.getByRole('dialog')).findByText('MSTR rally explained')

  await user.click(screen.getByRole('button', { name: 'New chat' }))

  expect(reset).toHaveBeenCalledTimes(1)
  expect(screen.queryByText('MSTR rally explained')).not.toBeInTheDocument()
  expect(screen.getByRole('textbox', { name: 'Google Finance question' })).toHaveValue(
    'Why is MSTR moving today?',
  )
  // The launcher card outside the (open, so aria-hidden) sheet drops its preview too.
  expect(
    screen.getByRole('button', { name: 'Ask Google Finance', hidden: true }),
  ).toBeInTheDocument()
})

test('New chat is available after a failed request too', async () => {
  const user = userEvent.setup()
  setHookState({ isError: true, error: new Error('Backend unavailable') })
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  expect(screen.getByRole('button', { name: 'New chat' })).toBeEnabled()
})

test('a preset chip fills the question without sending it', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'Why it went down' }))

  expect(screen.getByRole('textbox', { name: 'Google Finance question' })).toHaveValue(
    'Why has MSTR gone down today, and what is driving the selling?',
  )
  expect(mutateAsync).not.toHaveBeenCalled()
})

test('submits the preset question after a chip is picked', async () => {
  const user = userEvent.setup()
  mutateAsync.mockResolvedValue(success)
  renderWithProviders(<GoogleFinanceResearch ticker="NVDA" />)
  await openChat(user)

  await user.click(screen.getByRole('button', { name: 'After earnings' }))
  await user.click(screen.getByRole('button', { name: 'Submit' }))

  expect(mutateAsync).toHaveBeenCalledWith({
    question: 'What happened to NVDA after its most recent earnings report, and why?',
    history: [],
  })
})

test('marks the chip matching the current question as pressed', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  // The textarea is seeded with the first preset, so its chip starts pressed.
  expect(screen.getByRole('button', { name: "Today's move" })).toHaveAttribute(
    'aria-pressed',
    'true',
  )

  await user.click(screen.getByRole('button', { name: 'Key risks' }))

  expect(screen.getByRole('button', { name: 'Key risks' })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getByRole('button', { name: "Today's move" })).toHaveAttribute(
    'aria-pressed',
    'false',
  )
})

test('drops the pressed marker once the question is edited by hand', async () => {
  const user = userEvent.setup()
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  await user.type(screen.getByRole('textbox', { name: 'Google Finance question' }), ' Explain.')

  expect(screen.getByRole('button', { name: "Today's move" })).toHaveAttribute(
    'aria-pressed',
    'false',
  )
})

test('disables preset chips while a request is in flight', async () => {
  const user = userEvent.setup()
  setHookState({ isPending: true })
  renderWithProviders(<GoogleFinanceResearch ticker="MSTR" />)
  await openChat(user)

  expect(screen.getByRole('button', { name: 'Recent catalysts' })).toBeDisabled()
})
